### ISSUE TITLE
Move to v2 reporter?

### ISSUE THREAD

**Issue by badtant** [dylanb/react-axe#10]
Don't know the reason why v1 reporter is used now but I have a suggestion to move to v2 to be able to print more friendly messages with use of relatedNodes.

https://github.com/dequelabs/axe-core/issues/215

**Comment by badtant** [comment]
So, this is now merged. Time for a new release?

**Comment by badtant** [comment]
@dylanb when will there be a new release?

**Comment by dylanb** [comment]
done
