### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by reintroducing** [dylanb/react-axe#3]
So I got around to replacing react-a11y with react-axe in my project today and I immediately saw this after the replacement. It seems to point to line 20 in this screenshot:

https://www.dropbox.com/s/o0p4r7t6gso1uuy/Screenshot%202016-08-03%2020.51.17.png?dl=0

Let me know if you need any other information.

*UPDATE:* Sorry prior screenshot cut off the line numbers, new screenshot URL updated.

**Comment by dylanb** [comment]
That line is being inserted by webpack. I have just updated the library to use the latest axe-core. Can you see whether this fixes the problem?

**Comment by reintroducing** [comment]
I don't see any updates in this repo so I'm going to assume this pulls in a separate library through an XHR request because of that. That being said, it does not seem to have fixed it, I'm still getting the same issue.

**Comment by dylanb** [comment]
Are you pulling in the dependencies using npm? I only updated the npm version.

Also, if its still breaking, can you share the essential portions of your project that would allow me to reproduce this?

**Comment by reintroducing** [comment]
Yes, I'm pulling from npm, I see version 1.0.6 of react-axe in my node_modules.

In my main.js file I literally removed everything except for this and I'm still getting the error:
```
import React from 'react';

if (process.env.NODE_ENV === 'development') {
    const axe = require('react-axe');
    const ReactDOM = require('react-dom');

    axe(React, ReactDOM);
}
```

**Comment by reintroducing** [comment]
Ok, so quick update, I removed the offending lines from axe.js in my node_modules dir and then got a new error, `Uncaught ReferenceError: module is not defined` from basically the next definition, `if (( false ? "undefined" : _typeof(module)) === "object" && module.exports && typeof axeFunction.toString === "function") {`.  It's almost as if Webpack has no idea how to handle the module definitions (not sure I'm using the right terminology here).

Also worth noting is that react-axe actually does seem to be working as I do actually get the `New aXe issues` logged in my console but this error is definitely annoying.

**Comment by dylanb** [comment]
Yeah, it works fine in my projects but I am using browserify rather than webpack. Could you share your  build script with me?

**Comment by reintroducing** [comment]
Sure thing, here you go: https://www.dropbox.com/s/yqw99jenrxnfaat/react-axe-test.zip?dl=0

cd into it, `npm i && npm start`

**Comment by dylanb** [comment]
it looks like an incompatibility between axe-core and webpack 1.13. I am going to open a ticket in the axe-core project.

**Comment by dylanb** [comment]
@reintroducing I have now eliminated webpack 1.13 as the source of the problem on its own. axe-core works well with webpack 1.13 (I could share my example application with you if you're interested).

**Comment by dylanb** [comment]
@reintroducing I am trying to grok why your project seems to be not webpacking the axe-core (axe.js) file correctly. Do you have any idea what part of your (complex) configuration might be causing this?

**Comment by reintroducing** [comment]
I'm about to head on vacation for the next week and a half but when I return I'll simplify my config so we can pinpoint this.  Appreciate you taking a look.

**Comment by badtant** [comment]
I'm getting the same error

**Comment by dylanb** [comment]
@badtant do you have the same build configuration or a different one?

**Comment by badtant** [comment]
Hmm, hard to compare the configs.
When trying to do a production build with webpack i get the following:
SyntaxError: Name expected [./~/react-axe/index.js:109,0]

Been looking at line 109 but can't really understand what's wrong.

**Comment by dylanb** [comment]
@reintroducing looks like @badtant fixed your problem in the commit referenced above. Can you test this? If it works, I'll publish a new version to NPM

**Comment by dylanb** [comment]
yep, it fixes it
